# Generated by Django 3.0 on 2023-07-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20230726_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория'),
        ),
    ]
