# Generated by Django 3.0 on 2023-07-26 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='operation',
            field=models.CharField(choices=[('PURCHASE', 'Покупка'), ('RENT_1_MONTH', 'Аренда на 1 месяц'), ('RENT_3_MONTHS', 'Аренда на 3 месяца')], default='PURCHASE', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='rent_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость аренды'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
