# Generated by Django 3.0 on 2023-07-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20230726_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='operation',
            field=models.CharField(default='PURCHASE', max_length=20),
        ),
    ]
