# Generated by Django 3.0 on 2023-07-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_order_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст книги'),
        ),
    ]
