# Generated by Django 3.0 on 2023-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20230727_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
